import { auth, db } from "./firebase-config.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { doc, getDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const $=id=>document.getElementById(id);let uid="";
function show(type,msg){const el=$("message");el.className=`profile-message ${type}`;el.textContent=msg;}
function avatar(name,url){const box=$("profileAvatar"),top=$("topAvatar");if(url){box.innerHTML=`<img src="${String(url).replace(/"/g,"&quot;")}" alt="Profile">`;}else box.textContent=(name||"A").trim().charAt(0).toUpperCase()||"A";if(top)top.textContent=(name||"A").trim().charAt(0).toUpperCase()||"A";}
onAuthStateChanged(auth,async user=>{if(!user){location.href="../../login.html";return;}uid=user.uid;try{const snap=await getDoc(doc(db,"users",uid));if(!snap.exists())throw new Error("Admin profile not found.");const d=snap.data();if(String(d.role||"").trim().toLowerCase()!=="admin"||String(d.status||"").trim().toLowerCase()!=="active")throw new Error("This account is not an active admin.");$("adminId").value=d.adminId||"";$("email").value=user.email||d.email||"";$("name").value=d.name||"";$("phone").value=d.phone||d.contact||"";$("address").value=d.address||"";$("profilePicture").value=d.profilePicture||"";$("profileName").textContent=d.name||user.email||"Admin";$("profileEmail").textContent=user.email||d.email||"";$("topName").textContent=d.name||"Admin";avatar(d.name,d.profilePicture);}catch(e){show("err",e.message);}});
$("profileForm").addEventListener("submit",async e=>{e.preventDefault();const btn=$("saveBtn");btn.disabled=true;btn.textContent="Saving…";try{const name=$("name").value.trim();if(!name)throw new Error("Name is required.");await updateDoc(doc(db,"users",uid),{name,phone:$("phone").value.trim(),address:$("address").value.trim(),profilePicture:$("profilePicture").value.trim(),updatedAt:serverTimestamp(),updatedBy:uid});$("profileName").textContent=name;$("topName").textContent=name;avatar(name,$("profilePicture").value.trim());const old=JSON.parse(localStorage.getItem("riseEdgeUser")||"{}");localStorage.setItem("riseEdgeUser",JSON.stringify({...old,name}));show("ok","Profile updated successfully.");}catch(e){show("err",e.message||"Unable to update profile.");}finally{btn.disabled=false;btn.textContent="Save Changes";}});
$("logoutLink")?.addEventListener("click",async e=>{e.preventDefault();await signOut(auth);localStorage.removeItem("riseEdgeUser");localStorage.removeItem("riseEdgeAdmin");location.href="../../login.html";});
